include:
  - board: xiao_ble
    shield: trb_x9
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: trb_x9
  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-xiao_ble
  - board: xiao_ble
    shield: tester_xiao
    artifact-name: tester_xiao
